# Data Manipulation using Pandas and Numpy libraries

In any data science or data analysis project, the main task is to clean the data,format it in a way suitable for ml models perform some operations on it to handle the missing data then analyze the data,get insights from it.Pandas library is a powerful tool which gives us functionalities for manipulating data,analyzing data and makes it easier to clean,transform the data

In [ ]:
## Importing the both libraries
import pandas as pd
import numpy as np

In [ ]:
## Creating a dataframe
df = pd.read_csv('data.csv')
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

### Statistical Summary of data

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
## Datatypes of variables
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

### Missing Values

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [10]:
## Fill values
df.fillna(0)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [11]:
## Fill values with mean of the column
df['Sales']=df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product       Sales Region
0   2023-01-01        A   28.0  Product1  754.000000   East
1   2023-01-02        B   39.0  Product3  110.000000  North
2   2023-01-03        C   32.0  Product2  398.000000   East
3   2023-01-04        B    8.0  Product1  522.000000   East
4   2023-01-05        B   26.0  Product3  869.000000  North
5   2023-01-06        B   54.0  Product3  192.000000   West
6   2023-01-07        A   16.0  Product1  936.000000   East
7   2023-01-08        C   89.0  Product1  488.000000   West
8   2023-01-09        C   37.0  Product3  772.000000   West
9   2023-01-10        A   22.0  Product2  834.000000   West
10  2023-01-11        B    7.0  Product1  842.000000  North
11  2023-01-12        B   60.0  Product2  557.130435   West
12  2023-01-13        A   70.0  Product3  628.000000  South
13  2023-01-14        A   69.0  Product1  423.000000   East
14  2023-01-15        A   47.0  Product2  893.000000   West
15  2023-01-16        C    NaN  Product1  895.000000  North
16  2023-01-17        C   93.0  Product2  511.000000  South
17  2023-01-18        C    NaN  Product1  108.000000   West
18  2023-01-19        A   31.0  Product2  578.000000   West
19  2023-01-20        A   59.0  Product1  736.000000   East
20  2023-01-21        C   82.0  Product3  606.000000  South
21  2023-01-22        C   37.0  Product2  992.000000  South
22  2023-01-23        B   62.0  Product3  942.000000  North
23  2023-01-24        C   92.0  Product2  342.000000   West
24  2023-01-25        A   24.0  Product2  458.000000   East
25  2023-01-26        C   95.0  Product1  584.000000   West
26  2023-01-27        C   71.0  Product2  619.000000  North
27  2023-01-28        C   56.0  Product2  224.000000  North
28  2023-01-29        B    NaN  Product3  617.000000  North
29  2023-01-30        C   51.0  Product2  737.000000  South
30  2023-01-31        B   50.0  Product3  735.000000   West
31  2023-02-01        A   17.0  Product2  189.000000   West
32  2023-02-02        B   63.0  Product3  338.000000  South
33  2023-02-03        C   27.0  Product3  557.130435   East
34  2023-02-04        C   70.0  Product3  669.000000   West
35  2023-02-05        B   60.0  Product2  557.130435   West
36  2023-02-06        C   36.0  Product3  177.000000   East
37  2023-02-07        C    2.0  Product1  557.130435  North
38  2023-02-08        C   94.0  Product1  408.000000  South
39  2023-02-09        A   62.0  Product1  155.000000   West
40  2023-02-10        B   15.0  Product1  578.000000   East
41  2023-02-11        C   97.0  Product1  256.000000   East
42  2023-02-12        A   93.0  Product3  164.000000   West
43  2023-02-13        A   43.0  Product3  949.000000   East
44  2023-02-14        A   96.0  Product3  830.000000   East
45  2023-02-15        B   99.0  Product2  599.000000   West
46  2023-02-16        B    6.0  Product1  938.000000  South
47  2023-02-17        B   69.0  Product3  143.000000   West
48  2023-02-18        C   65.0  Product3  182.000000  North
49  2023-02-19        C   11.0  Product3  708.000000  North

In [14]:
## Renaming Columns
df = df.rename(columns={'Date':'Sale Date'})
df

     Sale Date Category  Value   Product       Sales Region
0   2023-01-01        A   28.0  Product1  754.000000   East
1   2023-01-02        B   39.0  Product3  110.000000  North
2   2023-01-03        C   32.0  Product2  398.000000   East
3   2023-01-04        B    8.0  Product1  522.000000   East
4   2023-01-05        B   26.0  Product3  869.000000  North
5   2023-01-06        B   54.0  Product3  192.000000   West
6   2023-01-07        A   16.0  Product1  936.000000   East
7   2023-01-08        C   89.0  Product1  488.000000   West
8   2023-01-09        C   37.0  Product3  772.000000   West
9   2023-01-10        A   22.0  Product2  834.000000   West
10  2023-01-11        B    7.0  Product1  842.000000  North
11  2023-01-12        B   60.0  Product2  557.130435   West
12  2023-01-13        A   70.0  Product3  628.000000  South
13  2023-01-14        A   69.0  Product1  423.000000   East
14  2023-01-15        A   47.0  Product2  893.000000   West
15  2023-01-16        C    NaN  Product1  895.000000  North
16  2023-01-17        C   93.0  Product2  511.000000  South
17  2023-01-18        C    NaN  Product1  108.000000   West
18  2023-01-19        A   31.0  Product2  578.000000   West
19  2023-01-20        A   59.0  Product1  736.000000   East
20  2023-01-21        C   82.0  Product3  606.000000  South
21  2023-01-22        C   37.0  Product2  992.000000  South
22  2023-01-23        B   62.0  Product3  942.000000  North
23  2023-01-24        C   92.0  Product2  342.000000   West
24  2023-01-25        A   24.0  Product2  458.000000   East
25  2023-01-26        C   95.0  Product1  584.000000   West
26  2023-01-27        C   71.0  Product2  619.000000  North
27  2023-01-28        C   56.0  Product2  224.000000  North
28  2023-01-29        B    NaN  Product3  617.000000  North
29  2023-01-30        C   51.0  Product2  737.000000  South
30  2023-01-31        B   50.0  Product3  735.000000   West
31  2023-02-01        A   17.0  Product2  189.000000   West
32  2023-02-02        B   63.0  Product3  338.000000  South
33  2023-02-03        C   27.0  Product3  557.130435   East
34  2023-02-04        C   70.0  Product3  669.000000   West
35  2023-02-05        B   60.0  Product2  557.130435   West
36  2023-02-06        C   36.0  Product3  177.000000   East
37  2023-02-07        C    2.0  Product1  557.130435  North
38  2023-02-08        C   94.0  Product1  408.000000  South
39  2023-02-09        A   62.0  Product1  155.000000   West
40  2023-02-10        B   15.0  Product1  578.000000   East
41  2023-02-11        C   97.0  Product1  256.000000   East
42  2023-02-12        A   93.0  Product3  164.000000   West
43  2023-02-13        A   43.0  Product3  949.000000   East
44  2023-02-14        A   96.0  Product3  830.000000   East
45  2023-02-15        B   99.0  Product2  599.000000   West
46  2023-02-16        B    6.0  Product1  938.000000  South
47  2023-02-17        B   69.0  Product3  143.000000   West
48  2023-02-18        C   65.0  Product3  182.000000  North
49  2023-02-19        C   11.0  Product3  708.000000  North

In [15]:
## Change datatypes
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df

     Sale Date Category  Value   Product       Sales Region  Value_new
0   2023-01-01        A   28.0  Product1  754.000000   East         28
1   2023-01-02        B   39.0  Product3  110.000000  North         39
2   2023-01-03        C   32.0  Product2  398.000000   East         32
3   2023-01-04        B    8.0  Product1  522.000000   East          8
4   2023-01-05        B   26.0  Product3  869.000000  North         26
5   2023-01-06        B   54.0  Product3  192.000000   West         54
6   2023-01-07        A   16.0  Product1  936.000000   East         16
7   2023-01-08        C   89.0  Product1  488.000000   West         89
8   2023-01-09        C   37.0  Product3  772.000000   West         37
9   2023-01-10        A   22.0  Product2  834.000000   West         22
10  2023-01-11        B    7.0  Product1  842.000000  North          7
11  2023-01-12        B   60.0  Product2  557.130435   West         60
12  2023-01-13        A   70.0  Product3  628.000000  South         70
13  2023-01-14        A   69.0  Product1  423.000000   East         69
14  2023-01-15        A   47.0  Product2  893.000000   West         47
15  2023-01-16        C    NaN  Product1  895.000000  North         51
16  2023-01-17        C   93.0  Product2  511.000000  South         93
17  2023-01-18        C    NaN  Product1  108.000000   West         51
18  2023-01-19        A   31.0  Product2  578.000000   West         31
19  2023-01-20        A   59.0  Product1  736.000000   East         59
20  2023-01-21        C   82.0  Product3  606.000000  South         82
21  2023-01-22        C   37.0  Product2  992.000000  South         37
22  2023-01-23        B   62.0  Product3  942.000000  North         62
23  2023-01-24        C   92.0  Product2  342.000000   West         92
24  2023-01-25        A   24.0  Product2  458.000000   East         24
25  2023-01-26        C   95.0  Product1  584.000000   West         95
26  2023-01-27        C   71.0  Product2  619.000000  North         71
27  2023-01-28        C   56.0  Product2  224.000000  North         56
28  2023-01-29        B    NaN  Product3  617.000000  North         51
29  2023-01-30        C   51.0  Product2  737.000000  South         51
30  2023-01-31        B   50.0  Product3  735.000000   West         50
31  2023-02-01        A   17.0  Product2  189.000000   West         17
32  2023-02-02        B   63.0  Product3  338.000000  South         63
33  2023-02-03        C   27.0  Product3  557.130435   East         27
34  2023-02-04        C   70.0  Product3  669.000000   West         70
35  2023-02-05        B   60.0  Product2  557.130435   West         60
36  2023-02-06        C   36.0  Product3  177.000000   East         36
37  2023-02-07        C    2.0  Product1  557.130435  North          2
38  2023-02-08        C   94.0  Product1  408.000000  South         94
39  2023-02-09        A   62.0  Product1  155.000000   West         62
40  2023-02-10        B   15.0  Product1  578.000000   East         15
41  2023-02-11        C   97.0  Product1  256.000000   East         97
42  2023-02-12        A   93.0  Product3  164.000000   West         93
43  2023-02-13        A   43.0  Product3  949.000000   East         43
44  2023-02-14        A   96.0  Product3  830.000000   East         96
45  2023-02-15        B   99.0  Product2  599.000000   West         99
46  2023-02-16        B    6.0  Product1  938.000000  South          6
47  2023-02-17        B   69.0  Product3  143.000000   West         69
48  2023-02-18        C   65.0  Product3  182.000000  North         65
49  2023-02-19        C   11.0  Product3  708.000000  North         11

In [16]:
##
df['New value']=df['Value'].apply(lambda x:x**2)

In [17]:
df

,Sale Date,Category,Value,Product,Sales,Region,Value_new,New value
0,2023-01-01,A,28.0,Product1,754.000000,East,28,784.0
1,2023-01-02,B,39.0,Product3,110.000000,North,39,1521.0
2,2023-01-03,C,32.0,Product2,398.000000,East,32,1024.0
3,2023-01-04,B,8.0,Product1,522.000000,East,8,64.0
4,2023-01-05,B,26.0,Product3,869.000000,North,26,676.0
5,2023-01-06,B,54.0,Product3,192.000000,West,54,2916.0
6,2023-01-07,A,16.0,Product1,936.000000,East,16,256.0
7,2023-01-08,C,89.0,Product1,488.000000,West,89,7921.0
8,2023-01-09,C,37.0,Product3,772.000000,West,37,1369.0
9,2023-01-10,A,22.0,Product2,834.000000,West,22,484.0
10,2023-01-11,B,7.0,Product1,842.000000,North,7,49.0
11,2023-01-12,B,60.0,Product2,557.130435,West,60,3600.0
12,2023-01-13,A,70.0,Product3,628.000000,South,70,4900.0
13,2023-01-14,A,69.0,Product1,423.000000,East,69,4761.0
14,2023-01-15,A,47.0,Product2,893.000000,West,47,2209.0
15,2023-01-16,C,NaN,Product1,895.000000,North,51,NaN
16,2023-01-17,C,93.0,Product2,511.000000,South,93,8649.0
17,2023-01-18,C,NaN,Product1,108.000000,West,51,NaN
18,2023-01-19,A,31.0,Product2,578.000000,West,31,961.0
19,2023-01-20,A,59.0,Product1,736.000000,East,59,3481.0
20,2023-01-21,C,82.0,Product3,606.000000,South,82,6724.0
21,2023-01-22,C,37.0,Product2,992.000000,South,37,1369.0
22,2023-01-23,B,62.0,Product3,942.000000,North,62,3844.0
23,2023-01-24,C,92.0,Product2,342.000000,West,92,8464.0
24,2023-01-25,A,24.0,Product2,458.000000,East,24,576.0
25,2023-01-26,C,95.0,Product1,584.000000,West,95,9025.0
26,2023-01-27,C,71.0,Product2,619.000000,North,71,5041.0
27,2023-01-28,C,56.0,Product2,224.000000,North,56,3136.0
28,2023-01-29,B,NaN,Product3,617.000000,North,51,NaN
29,2023-01-30,C,51.0,Product2,737.000000,South,51,2601.0
30,2023-01-31,B,50.0,Product3,735.000000,West,50,2500.0
31,2023-02-01,A,17.0,Product2,189.000000,West,17,289.0
32,2023-02-02,B,63.0,Product3,338.000000,South,63,3969.0
33,2023-02-03,C,27.0,Product3,557.130435,East,27,729.0
34,2023-02-04,C,70.0,Product3,669.000000,West,70,4900.0
35,2023-02-05,B,60.0,Product2,557.130435,West,60,3600.0
36,2023-02-06,C,36.0,Product3,177.000000,East,36,1296.0
37,2023-02-07,C,2.0,Product1,557.130435,North,2,4.0
38,2023-02-08,C,94.0,Product1,408.000000,South,94,8836.0
39,2023-02-09,A,62.0,Product1,155.000000,West,62,3844.0
40,2023-02-10,B,15.0,Product1,578.000000,East,15,225.0
41,2023-02-11,C,97.0,Product1,256.000000,East,97,9409.0
42,2023-02-12,A,93.0,Product3,164.000000,West,93,8649.0
43,2023-02-13,A,43.0,Product3,949.000000,East,43,1849.0
44,2023-02-14,A,96.0,Product3,830.000000,East,96,9216.0
45,2023-02-15,B,99.0,Product2,599.000000,West,99,9801.0
46,2023-02-16,B,6.0,Product1,938.000000,South,6,36.0
47,2023-02-17,B,69.0,Product3,143.000000,West,69,4761.0
48,2023-02-18,C,65.0,Product3,182.000000,North,65,4225.0
49,2023-02-19,C,11.0,Product3,708.000000,North,11,121.0

In [18]:
## Data Aggregating and Grouping
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [20]:
val = df.groupby(['Product','Region'])['Value'].sum()
print(val)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [21]:
## Multiple aggregate functions
df.groupby('Region')['Value'].agg(['mean','sum','count'])

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [22]:
### Merging and Joining Dataframes

In [23]:
df1 = pd.DataFrame({'Key':['A','B','C'],'Value':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'],'Value':[4,5,6]})

In [24]:
## Merge dataframes on key columns
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

In [25]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [26]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [27]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6